#!perl

use v5.28.0;
use warnings;

use Test2::V0;

use Weasel::Driver::Selenium4;

my $drv = Weasel::Driver::Selenium4->new(
    caps => {
        remote_server_addr => 'localhost',
        port => 4444,
        driver => 'Auto',
        browser => 'chrome',
        extra_capabilities => {
            'goog:chromeOptions' => {
                args => [ '--headless=new' ]
            }
        }
    });

ok($drv, 'Driver correctly allocated');

my $started = lives { $drv->start; };
ok($started, 'Driver correctly started');

my $gotten = lives { $drv->get('https://example.com'); };
ok($gotten, 'Correctly retrieved https://example.com');

my @body;
my $finders = lives { @body = $drv->find_all( '/html', 'body', 'css selector' ) };
ok( $finders, 'Correctly searched for <body>' );
ok( (@body == 1), 'Correctly found <body>' );

my ($body) = @body;
my $clicked = lives { $drv->click( $body ) };
ok( $clicked, 'Successfully clicked <body>' );

done_testing;
